export const QUOTES: string[] = [
  "•MOVE QUIETLY •WORK LOUDLY",
  "•DISCIPLINE BEATS MOTIVATION",
  "•SMALL STEPS •BIG RESULTS",
  "•KEEP LEARNING •KEEP LEVELING UP",
  "•FOCUS •EXECUTE •REPEAT",
  "•TODAY EFFORT •TOMORROW POWER",
  "•DREAM BIG •BUILD DAILY",
  "•NO EXCUSES •JUST PROGRESS",
  "•BE CONSISTENT •NOT PERFECT",
  "•SKILLS PAY BILLS",
  "•LEARN FAST •SHIP FAST",
  "•HARD WORK •SMART WORK",
  "•UPGRADE YOURSELF EVERY DAY",
  "•STAY HUMBLE •STAY HUNGRY",
  "•FAIL QUICK •IMPROVE QUICK",
  "•ENERGY IN •RESULTS OUT",
  "•ONE DAY OR DAY ONE",
  "•YOUR FUTURE NEEDS YOUR WORK",
  "•CALM MIND •SHARP MOVES",
  "•DON’T STOP WHEN TIRED •STOP WHEN DONE",
  "•MAKE IT SIMPLE •MAKE IT STRONG",
  "•KEEP YOUR TARGET IN SIGHT",
  "•CONSISTENCY IS A SUPERPOWER",
  "•LEARN •BUILD •REPEAT",
  "•LEVEL UP MODE ON",
  "•YOU CAN •YOU WILL",
  "•WORK IN SILENCE •WIN IN PUBLIC",
  "•FOCUS ON SYSTEMS •NOT MOOD",
  "•START NOW •FIX LATER",
  "•PROGRESS EVERY DAY",
];

export function pickQuote(seed?: number) {
  const s = seed ?? Date.now();
  return QUOTES[Math.abs(s) % QUOTES.length];
}
